# Generated by Django 5.1.7 on 2025-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_add_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
