# Generated by Django 5.1.7 on 2025-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_add_prompt_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chatName",
                    models.CharField(default="Chat Assistant", max_length=255),
                ),
                ("colorPrimary", models.CharField(default="#4B5563", max_length=50)),
                ("buttonBg", models.CharField(default="#4B5563", max_length=50)),
                (
                    "welcomeMessage",
                    models.TextField(default="Welcome! How can I help you today?"),
                ),
                (
                    "disclaimerTitle",
                    models.CharField(
                        default="Welcome to the Chat Assistant", max_length=255
                    ),
                ),
                (
                    "disclaimerIntro",
                    models.TextField(
                        default="Please review the following information before we start:"
                    ),
                ),
                ("disclaimerPoints", models.JSONField(default=list)),
                (
                    "acceptButtonText",
                    models.CharField(default="Accept and Continue", max_length=100),
                ),
                ("sendButtonText", models.CharField(default="Send", max_length=100)),
                (
                    "footerDisclaimer",
                    models.TextField(
                        default="This AI assistant provides information based on publicly available data."
                    ),
                ),
                (
                    "privacyPolicyText",
                    models.CharField(default="Privacy Policy", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
