# Generated by Django 5.1.7 on 2025-04-13 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_backgroundimage_user_conversation_user_document_user_and_more"),
    ]

    operations = []
